# -*- coding: utf-8 -*-
"""CIE-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FgK_L5MxnrmxrZV87qpPRI_FHE7xCNTf
"""

import pandas as pd
data={'productname'   :['mobile','tshirts','detergent','tv','pant'],
      'category'      :['electronics','clothing','home & kitchen','elkectronics','clothing'],
      'price'        :[5000,150,50,10000,300],
      'quantity_sold':[1,3,2,5,3],
}
df=pd.DataFrame(data)
df['total_revenue']=df['price']*df['quantity_sold']
pd.pivot_table(df,index='category',values=['total_revenue','price'],aggfunc={'total_revenue':'sum','price':'mean'})

import pandas as pd
data={'productname'   :['mobile','tshirts','detergent','tv','pant'],
      'category'      :['electronics','clothing','home & kitchen','elkectronics','clothing'],
      'price'        :[5000,150,50,10000,300],
      ' qutntity sold':[1,3,2,5,3],
}
df=pd.DataFrame(data)
pd.pivot_table(df,index='category',values='price',aggfunc='mean')

import matplotlib.pyplot as plt
import pandas as pd

df=pd.read_csv('mtcars.csv')
plt.hist(df['mpg'],bins=30,edgecolor='k')
plt.title('Histogram of mpg (miles per gallon)')
plt.xlabel('mpg')
plt.ylabel('Frequency')
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
import pandas as pd

df=pd.read_csv('mtcars.csv')
plt.scatter(df['mpg'],df['wt'],color='orange')
plt.title('Scatter plot')
plt.xlabel('mpg')
plt.ylabel('wt')
plt.show()

import matplotlib.pyplot as plt
import pandas as pd

df=pd.read_csv('mtcars.csv')
plt.boxplot(df['mpg'])
plt.title('BOX Plot')
plt.xlabel('mpg')
plt.show()

import matplotlib.pyplot as plt
import pandas as pd

df=pd.read_csv('mtcars.csv')
Transmission_counts=df['am'].value_counts()
Transmission_counts.plot(kind='bar',color='orange')
plt.title('Frequency Distribution of Transmission media')
plt.xlabel('Transmission media')
plt.ylabel('Frequency')
plt.show()